name = "JuBox"
version = "25.11.11"
authors = ["Janis Erdmanis <janiserdmanis@protonmail.ch>"]

[deps]
AlgebraOfGraphics = "cbdf2221-f076-402e-a563-3d30da359d67"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Infiltrator = "5903a43b-9cc3-4c30-8d17-598619ec4e9b"
Integrals = "de52edbc-65ea-441a-8357-d3a637375a31"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
Mooncake = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
QuantumOptics = "6e0679c1-51ea-5a7c-ac74-d61b76210b0c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"

[compat]
AlgebraOfGraphics = "0.11.9"
CairoMakie = "0.15.6"
DataFrames = "1.8.1"
DifferentialEquations = "7.17.0"
GLMakie = "0.13.6"
Graphs = "1.13.1"
Infiltrator = "1.9.4"
Makie = "0.24.6"
ModelingToolkit = "10.26.1"
QuantumOptics = "1.2.4"
Revise = "3.12.1"
WGLMakie = "0.13.6"
